// FileListViewWindowClass.h

#pragma once

#include <windows.h>
#include <commctrl.h>

#include <windows.h>

#include "ListViewWindowClass.h"

#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT								NULL
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU								NULL
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE						LVS_EX_FULLROWSELECT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE								( WS_VISIBLE | WS_CHILD | WS_BORDER | LVS_REPORT )
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT								CW_USEDEFAULT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP									CW_USEDEFAULT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH								CW_USEDEFAULT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT								CW_USEDEFAULT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM							NULL

#define FILE_LIST_VIEW_WINDOW_CLASS_ADD_FILES_STATUS_MESSAGE_FORMAT_STRING		"%s (%d files)"
#define FILE_LIST_VIEW_WINDOW_CLASS_MODIFIED_TEXT_FORMAT_STRING					"%04d/%02d/%02d %02d:%02d:%02d"

#define FILE_LIST_VIEW_WINDOW_CLASS_CLASS_COLUMN_TITLES							{ "Name", "Modified" }

typedef enum
{
	FILE_LIST_VIEW_WINDOW_CLASS_NAME_COLUMN_ID = 0,
	FILE_LIST_VIEW_WINDOW_CLASS_MODIFIED_COLUMN_ID,

	FILE_LIST_VIEW_WINDOW_CLASS_NUMBER_OF_COLUMNS

} FILE_LIST_VIEW_WINDOW_CLASS_COLUMNS;

class FileListViewWindow : public ListViewWindow
{
public:
	FileListViewWindow();
	~FileListViewWindow();

	int AddFiles( LPCTSTR lpszFolderPath, LPCTSTR lpszFileFilter = ALL_FILES_FILTER );

	BOOL Create( HWND hWndParent, HINSTANCE hInstance, LPCTSTR lpszWindowText = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT, HMENU hMenu = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU, DWORD dwExStyle = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE, DWORD dwStyle = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE, int nLeft = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT, int nTop = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP, int nWidth = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH, int nHeight = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT, LPVOID lpParam = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM );

	int GetItemPath( int nWhichItem, LPTSTR lpszItemPath );

	int GetItemPath(LPTSTR lpszItemPath );

	BOOL HandleNotifyMessage( WPARAM, LPARAM lParam, void( *lpSelectionChangedFunction )( LPCTSTR lpszItemPath ), void( *lpDoubleClickFunction )( LPCTSTR lpszItemPath ) );

	BOOL Move( int nLeft, int nTop, int nWidth, int nHeight, BOOL bRepaint = TRUE );

protected:
	LPTSTR m_lpszParentFolderPath;

}; // End of class FileListViewWindow
