// FileListViewWindowClass.h

#pragma once

#include <windows.h>

#include "..\Common\Ascii.h"
#include "..\Common\Common.h"

#include "ListViewWindowClass.h"

#define FILE_LIST_VIEW_WINDOW_CLASS_NAME										WC_LISTVIEW
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT								NULL
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU								NULL
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE						LVS_EX_FULLROWSELECT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE								( WS_VISIBLE | WS_CHILD | WS_BORDER | LVS_REPORT )
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT								CW_USEDEFAULT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP									CW_USEDEFAULT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH								CW_USEDEFAULT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT								CW_USEDEFAULT
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM							NULL
#define FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_COLUMN_WIDTH						100

#define FILE_LIST_VIEW_WINDOW_CLASS_CLASS_COLUMN_TITLES							{ "Name", "Modified" }

typedef enum
{
	FILE_LIST_VIEW_WINDOW_CLASS_NAME_COLUMN_ID = 0,
	FILE_LIST_VIEW_WINDOW_CLASS_MODIFIED_COLUMN_ID,

	FILE_LIST_VIEW_WINDOW_CLASS_NUMBER_OF_COLUMNS

} FILE_LIST_VIEW_WINDOW_CLASS_COLUMNS;

class FileListViewWindow : public ListViewWindow
{
public:
	FileListViewWindow();
	~FileListViewWindow();

	FileListViewWindow& operator = ( HWND hWnd );

	BOOL operator == ( HWND hWnd );

	BOOL operator != ( HWND hWnd );

	operator HWND();

	BOOL Create( HWND hWndParent, HINSTANCE hInstance, LPCTSTR lpszWindowText = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT, HMENU hMenu = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU, DWORD dwExStyle = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE, DWORD dwStyle = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE, int nLeft = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT, int nTop = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP, int nWidth = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH, int nHeight = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT, LPVOID lpParam = FILE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM );

	BOOL HandleNotifyMessage( WPARAM wParam, LPARAM lParam, void( *lpSelectionChangedFunction )( LPCTSTR lpszItemText ), void( *lpDoubleClickFunction )( LPCTSTR lpszItemText ), PFNLVCOMPARE lpCompareFunction );

protected:

}; // End of class FileListViewWindow
