// TemplateListViewWindowClass.h

#pragma once

#include <windows.h>

#include "..\Common\Ascii.h"
#include "..\Common\Common.h"

#include "ListViewWindowClass.h"

#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_NAME									WC_LISTVIEW
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT							NULL
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU							NULL
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE					LVS_EX_FULLROWSELECT
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE							( WS_VISIBLE | WS_CHILD | WS_BORDER | LVS_REPORT )
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT							CW_USEDEFAULT
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP								CW_USEDEFAULT
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH							CW_USEDEFAULT
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT							CW_USEDEFAULT
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM						NULL
#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_COLUMN_WIDTH					100

#define TEMPLATE_LIST_VIEW_WINDOW_CLASS_CLASS_COLUMN_TITLES						{ "URL", "Local File" }

typedef enum
{
	TEMPLATE_LIST_VIEW_WINDOW_CLASS_URL_COLUMN_ID = 0,
	TEMPLATE_LIST_VIEW_WINDOW_CLASS_LOCAL_FILE_COLUMN_ID,

	TEMPLATE_LIST_VIEW_WINDOW_CLASS_NUMBER_OF_COLUMNS

} TEMPLATE_LIST_VIEW_WINDOW_CLASS_COLUMNS;

class TemplateListViewWindow : public ListViewWindow
{
public:
	TemplateListViewWindow();
	~TemplateListViewWindow();

	TemplateListViewWindow& operator = ( HWND hWnd );

	BOOL operator == ( HWND hWnd );

	BOOL operator != ( HWND hWnd );

	operator HWND();

	BOOL Create( HWND hWndParent, HINSTANCE hInstance, LPCTSTR lpszWindowText = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TEXT, HMENU hMenu = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_MENU, DWORD dwExStyle = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_EXTENDED_STYLE, DWORD dwStyle = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_STYLE, int nLeft = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LEFT, int nTop = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_TOP, int nWidth = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_WIDTH, int nHeight = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_HEIGHT, LPVOID lpParam = TEMPLATE_LIST_VIEW_WINDOW_CLASS_DEFAULT_LP_PARAM );

	BOOL HandleNotifyMessage( WPARAM wParam, LPARAM lParam, void( *lpSelectionChangedFunction )( LPCTSTR lpszItemText ), void( *lpDoubleClickFunction )( LPCTSTR lpszItemText ), PFNLVCOMPARE lpCompareFunction );

protected:

}; // End of class TemplateListViewWindow
